In [1]:
import pandas as pd
import sklearn.metrics.pairwise as pair
import sklearn.preprocessing as prep

In [2]:
movies=pd.read_csv('movies.csv')
movies.drop(columns=['genres'],inplace=True)
movies

      movieId                                      title
0           1                           Toy Story (1995)
1           2                             Jumanji (1995)
2           3                    Grumpier Old Men (1995)
3           4                   Waiting to Exhale (1995)
4           5         Father of the Bride Part II (1995)
...       ...                                        ...
9737   193581  Black Butler: Book of the Atlantic (2017)
9738   193583               No Game No Life: Zero (2017)
9739   193585                               Flint (2017)
9740   193587        Bungo Stray Dogs: Dead Apple (2018)
9741   193609        Andrew Dice Clay: Dice Rules (1991)

[9742 rows x 2 columns]

In [3]:
min_relevance=0.2
genome=pd.read_csv('tag_genome.csv',error_bad_lines=False,engine='python')
genome.query(expr='relevance>@min_relevance',inplace=True)
genome

/usr/local/lib/python3.8/dist-packages/IPython/core/interactiveshell.py:3326: FutureWarning: The error_bad_lines argument has been deprecated and will be removed in a future version.


  exec(code_obj, self.user_global_ns, self.user_ns)

          movieId        tag  relevance
5               1      1950s    0.24775
7               1      1970s    0.27250
8               1      1980s    0.21275
10              1         3d    0.56750
12              1        80s    0.20300
...           ...        ...        ...
12413615   175197      weird    0.27775
12413619   175197  whimsical    0.20225
12413624   175197    witches    0.52900
12413626   175197    wizards    0.30775
12413634   175197    writers    0.36350

[2178319 rows x 3 columns]

In [4]:
relevant_tags=genome['tag'].values
relevant_tags

array(['1950s', '1970s', '1980s', ..., 'witches', 'wizards', 'writers'],
      dtype=object)

In [5]:
tags=pd.read_csv('tags.csv')
tags.drop(columns=['timestamp'],inplace=True)
tags

        userId  movieId                         tag
0       144473      933                 hw classics
1       144473      933            alfred hitchcock
2       144473    49272             guilty pleasure
3       144473     8228  not available from netflix
4       144473     7925            in netflix queue
...        ...      ...                         ...
628152  157305     3147                       Owned
628153  157305     3147              don't remember
628154  157305     3147             Worst film ever
628155  157305     3949      oscar (best directing)
628156  157305     3147      oscar (best directing)

[628157 rows x 3 columns]

In [6]:
tags.query(expr='tag in @relevant_tags',inplace=True)

In [7]:
movies_w_tags=movies.merge(tags,on=['movieId'])
movies_w_tags

        movieId                            title  userId          tag
0             1                 Toy Story (1995)  145552       clever
1             1                 Toy Story (1995)  144150  time travel
2             1                 Toy Story (1995)  144150    animation
3             1                 Toy Story (1995)  144150       comedy
4             1                 Toy Story (1995)  144150      fantasy
...         ...                              ...     ...          ...
224082   179819  Star Wars: The Last Jedi (2017)  144824    political
224083   180095                    Wonder (2017)  147195     children
224084   180095                    Wonder (2017)  147195     bullying
224085   182823                    Bright (2017)  147195      fantasy
224086   182823                    Bright (2017)  147195       action

[224087 rows x 4 columns]

In [8]:
#movies_data=pd.read_csv('movies.csv')
#movies_data.drop(columns=['genres'],inplace=True)
#movies_data

In [9]:
#tags_data=pd.read_csv('tags.csv')
#tags_data.drop(columns=['timestamp'],inplace=True)
#tags_data

In [10]:
#movies_w_tags=movies_data.merge(tags_data,on=['movieId'])
#movies_w_tags

In [11]:
movie_tag_encoder=prep.OneHotEncoder(sparse=False)
movies_encoded_tags=movie_tag_encoder.fit_transform(movies_w_tags[['tag']])
enc_tag_frame=pd.DataFrame(data=movies_encoded_tags,\
                           columns=movie_tag_encoder.get_feature_names_out())
enc_tag_frame

,tag_007,tag_007 (series),tag_18th century,tag_1920s,tag_1930s,tag_1950s,tag_1960s,tag_1970s,tag_1980s,tag_19th century,...,tag_world politics,tag_world war i,tag_world war ii,tag_writer's life,tag_writers,tag_writing,tag_wuxia,tag_wwii,tag_zombie,tag_zombies
0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
224082,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
224083,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
224084,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
224085,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
224086,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [12]:
movies_w_1_tag=movies_w_tags.join(enc_tag_frame)
movies_w_1_tag.drop(columns=['tag'],inplace=True)
movies_w_1_tag

,movieId,title,userId,tag_007,tag_007 (series),tag_18th century,tag_1920s,tag_1930s,tag_1950s,tag_1960s,...,tag_world politics,tag_world war i,tag_world war ii,tag_writer's life,tag_writers,tag_writing,tag_wuxia,tag_wwii,tag_zombie,tag_zombies
0,1,Toy Story (1995),145552,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,1,Toy Story (1995),144150,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,1,Toy Story (1995),144150,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,1,Toy Story (1995),144150,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,1,Toy Story (1995),144150,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
224082,179819,Star Wars: The Last Jedi (2017),144824,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
224083,180095,Wonder (2017),147195,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
224084,180095,Wonder (2017),147195,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
224085,182823,Bright (2017),147195,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
224086,182823,Bright (2017),147195,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [13]:
content_data=movies_w_1_tag.drop(columns=['userId']).groupby(['movieId']).sum()
content_data

,tag_007,tag_007 (series),tag_18th century,tag_1920s,tag_1930s,tag_1950s,tag_1960s,tag_1970s,tag_1980s,tag_19th century,...,tag_world politics,tag_world war i,tag_world war ii,tag_writer's life,tag_writers,tag_writing,tag_wuxia,tag_wwii,tag_zombie,tag_zombies
movieId,,,,,,,,,,,,,,,,,,,,,
1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
5,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
175661,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
176371,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
179819,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
180095,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
182823,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [14]:
user_data=movies_w_1_tag.drop(columns=['movieId']).groupby(['userId']).sum()
user_data

,tag_007,tag_007 (series),tag_18th century,tag_1920s,tag_1930s,tag_1950s,tag_1960s,tag_1970s,tag_1980s,tag_19th century,...,tag_world politics,tag_world war i,tag_world war ii,tag_writer's life,tag_writers,tag_writing,tag_wuxia,tag_wwii,tag_zombie,tag_zombies
userId,,,,,,,,,,,,,,,,,,,,,
100008,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
100500,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
100593,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
100602,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
100610,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
206067,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
206190,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
206212,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
206420,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
206715,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [15]:
#user_data=movies_w_1_tag.drop(columns=['movieId']).groupby(['userId']).sum()
#user_data

In [16]:
distances=pair.euclidean_distances(user_data,content_data)
distances

array([[127.4441054 ,  39.2173431 ,   8.18535277, ...,   1.41421356,
          1.73205081,   1.73205081],
       [127.4441054 ,  39.2173431 ,   8.18535277, ...,   1.41421356,
          1.73205081,   1.73205081],
       [127.4441054 ,  39.2173431 ,   8.18535277, ...,   1.41421356,
          1.73205081,   1.73205081],
       ...,
       [127.59702191,  39.7617907 ,  10.48808848, ...,   6.70820393,
          6.78232998,   6.78232998],
       [127.4441054 ,  39.2173431 ,   8.18535277, ...,   1.41421356,
          1.73205081,   1.73205081],
       [127.45979758,  39.08964057,   8.42614977, ...,   2.44948974,
          2.64575131,   2.64575131]])

In [17]:
distance_frame=pd.DataFrame(distances,index=pd.Index(user_data.index.values,name='UserID'),columns=pd.Index(content_data.index.values,name='MovieID'))
distance_frame

MovieID,1,2,3,4,5,6,7,8,9,10,...,170945,173291,173925,174055,175303,175661,176371,179819,180095,182823
UserID,,,,,,,,,,,,,,,,,,,,,
100008,127.444105,39.217343,8.185353,2.449490,11.090537,28.442925,15.652476,1.732051,2.236068,46.743984,...,1.732051,1.414214,1.414214,3.162278,1.414214,2.236068,3.872983,1.414214,1.732051,1.732051
100500,127.444105,39.217343,8.185353,2.449490,11.090537,28.442925,15.652476,1.732051,2.236068,46.743984,...,1.732051,1.414214,1.414214,3.162278,1.414214,2.236068,3.872983,1.414214,1.732051,1.732051
100593,127.444105,39.217343,8.185353,2.449490,11.090537,28.442925,15.652476,1.732051,2.236068,46.743984,...,1.732051,1.414214,1.414214,3.162278,1.414214,2.236068,3.872983,1.414214,1.732051,1.732051
100602,127.444105,39.217343,8.185353,2.449490,11.090537,28.442925,15.652476,1.732051,2.236068,46.743984,...,1.732051,1.414214,1.414214,3.162278,1.414214,2.236068,3.872983,1.414214,1.732051,1.732051
100610,127.444105,39.217343,8.185353,2.449490,11.090537,28.442925,15.652476,1.732051,2.236068,46.743984,...,1.732051,1.414214,1.414214,3.162278,1.414214,2.236068,3.872983,1.414214,1.732051,1.732051
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
206067,127.444105,39.217343,8.185353,2.449490,11.090537,28.442925,15.652476,1.732051,2.236068,46.743984,...,1.732051,1.414214,1.414214,3.162278,1.414214,2.236068,3.872983,1.414214,1.732051,1.732051
206190,127.444105,39.217343,8.185353,2.449490,11.090537,28.442925,15.652476,1.732051,2.236068,46.743984,...,1.732051,1.414214,1.414214,3.162278,1.414214,2.236068,3.872983,1.414214,1.732051,1.732051
206212,127.597022,39.761791,10.488088,7.000000,12.884099,27.928480,16.970563,6.782330,6.928203,47.159304,...,6.782330,6.708204,6.708204,7.280110,6.708204,6.928203,7.211103,6.708204,6.782330,6.782330
206420,127.444105,39.217343,8.185353,2.449490,11.090537,28.372522,15.652476,1.732051,2.236068,46.743984,...,1.732051,1.414214,1.414214,3.162278,1.414214,2.236068,3.872983,1.414214,1.732051,1.732051
206715,127.459798,39.089641,8.426150,3.162278,11.269428,28.513155,15.779734,2.236068,3.000000,46.786750,...,2.645751,2.449490,2.449490,3.741657,2.449490,3.000000,4.358899,2.449490,2.645751,2.645751

EVALUATION:

Mean Distance to User's Most Highly Recommended Movie

In [18]:
distance_frame.min(axis=1)

UserID
100008    1.000000
100500    1.000000
100593    0.000000
100602    1.414214
100610    1.414214
            ...
206067    0.000000
206190    1.414214
206212    5.291503
206420    1.000000
206715    2.000000
Length: 7431, dtype: float64

In [19]:
distance_frame.min(axis=1).mean()

4.029075551609354

EXAMPLE RECS

In [20]:
user_to_rec=100726
recced_movies=distance_frame.sort_values(by=user_to_rec,axis=1).columns.values[:5]
recced_movies

array([114044,  36509,  26603,  82499,   1594])

In [21]:
recced_names=[]
for i in recced_movies:
  name=movies.query('movieId==@i')['title'].values[0]
  recced_names.append(name)
recced_names

['Honeymoon (2014)',
 'Cave, The (2005)',
 'Prince of Darkness (1987)',
 'How Do You Know (2010)',
 'In the Company of Men (1997)']

In [22]:
user_data.sort_values(by=user_to_rec,axis=1,ascending=False).query('userId==@user_to_rec')

,tag_predictable,tag_not as good as the first,tag_rape,tag_based on book,tag_pointless,tag_overrated,tag_not funny,tag_boring,tag_stupid,tag_cheesy,...,tag_fascism,tag_fashion,tag_fast paced,tag_father daughter relationship,tag_father son relationship,tag_father-son relationship,tag_fbi,tag_feel good movie,tag_feel-good,tag_zombies
userId,,,,,,,,,,,,,,,,,,,,,
100726,3.0,2.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [23]:
content_data.sort_values(by=114044,axis=1,ascending=False).query('movieId==114044')

,tag_predictable,tag_boring,tag_007,tag_oscar (best editing),tag_oscar (best picture),tag_oscar (best music - original song),tag_oscar (best music - original score),tag_oscar (best foreign language film),tag_oscar (best effects - visual effects),tag_oscar (best directing),...,tag_farce,tag_fascism,tag_fashion,tag_fast paced,tag_father daughter relationship,tag_father son relationship,tag_father-son relationship,tag_fbi,tag_feel good movie,tag_zombies
movieId,,,,,,,,,,,,,,,,,,,,,
114044,2.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [24]:
content_data.sort_values(by=36509,axis=1,ascending=False).query('movieId==36509')

,tag_rape,tag_predictable,tag_oscar (best cinematography),tag_oscar (best music - original song),tag_oscar (best music - original score),tag_oscar (best foreign language film),tag_oscar (best effects - visual effects),tag_oscar (best editing),tag_oscar (best directing),tag_007,...,tag_fantasy world,tag_farce,tag_fascism,tag_fashion,tag_fast paced,tag_father daughter relationship,tag_father son relationship,tag_father-son relationship,tag_fbi,tag_zombies
movieId,,,,,,,,,,,,,,,,,,,,,
36509,2.0,2.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [25]:
content_data.sort_values(by=26603,axis=1,ascending=False).query('movieId==26603')

,tag_predictable,tag_007,tag_oscar (best directing),tag_oscar (best picture),tag_oscar (best music - original song),tag_oscar (best music - original score),tag_oscar (best foreign language film),tag_oscar (best effects - visual effects),tag_oscar (best editing),tag_oscar (best cinematography),...,tag_fantasy world,tag_farce,tag_fascism,tag_fashion,tag_fast paced,tag_father daughter relationship,tag_father son relationship,tag_father-son relationship,tag_fbi,tag_zombies
movieId,,,,,,,,,,,,,,,,,,,,,
26603,2.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [26]:
content_data.sort_values(by=82499,axis=1,ascending=False).query('movieId==82499')

,tag_predictable,tag_love triangles,tag_007,tag_oscar (best editing),tag_oscar (best picture),tag_oscar (best music - original song),tag_oscar (best music - original score),tag_oscar (best foreign language film),tag_oscar (best effects - visual effects),tag_oscar (best directing),...,tag_fantasy world,tag_farce,tag_fascism,tag_fashion,tag_fast paced,tag_father daughter relationship,tag_father son relationship,tag_father-son relationship,tag_fbi,tag_zombies
movieId,,,,,,,,,,,,,,,,,,,,,
82499,2.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [27]:
content_data.sort_values(by=1594,axis=1,ascending=False).query('movieId==1594')

,tag_predictable,tag_psychological,tag_007,tag_oscar (best directing),tag_oscar (best music - original song),tag_oscar (best music - original score),tag_oscar (best foreign language film),tag_oscar (best effects - visual effects),tag_oscar (best editing),tag_oscar (best cinematography),...,tag_fantasy world,tag_farce,tag_fascism,tag_fashion,tag_fast paced,tag_father daughter relationship,tag_father son relationship,tag_father-son relationship,tag_fbi,tag_zombies
movieId,,,,,,,,,,,,,,,,,,,,,
1594,2.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0